M48
; DRILL file KiCad 10.0.3 date 2026-05-24T03:38:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-24T03:38:14-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X119.19Y-80.8
X129.35Y-80.8
T2
X124.27Y-80.8
M30
